name: clubhouse.com

on:
    push:
      branches:
        - 'main'

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 3600
    steps:
      - name: Get current date
        id: date
        run:  echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - run: |
          mkdir -p ~/result/amass
          mkdir -p ~/result/httpx
          

      - name: Amass - Enumeration
        uses: r00t-life/amass-action@main
        with:
          domains: clubhouse.com
          brute: false
          ipv4: false
          output: ~/result/amass/clubhouse.com-${{ steps.date.outputs.date }}.txt
      
      - name: Httpx - Enumeration
        run:  |
          cat ~/result/amass/clubhouse.com-${{ steps.date.outputs.date }}.txt | httpx -title -status-code -tech-detect -follow-redirects -silent -p 80,443,8080,81,82,83,8443,8888,8000,10443,9200 -o ~/result/httpx/clubhouse.com-${{ steps.date.outputs.date }}.txt

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: clubhouse.com-${{ steps.date.outputs.date }}
          path: ~/result/**/*
      
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project amass enum clubhouse.com has been done.'