name: pingan.com

on:
    workflow_dispatch:

jobs:
  pingan-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 3600
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - run: |
          mkdir -p ~/result/amass
          mkdir -p ~/result/httpx

      - name: Amass - Enumeration
        uses: r00t-life/amass-action@main
        with:
          domains: pingan.com
          brute: false
          ipv4: false
          output: ~/result/amass/amass.txt
      
      - name: Httpx - Enumeration
        run:  |
          cat ~/result/amass/amass.txt | httpx -o ~/result/httpx/httpx.txt

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: amass-result
          path: ~/result/**/*
      
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project amass enum instacart.com has been done.'