name: recon

on:
    push:
      branches:
        - 'main'

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 3600
    steps:
      - name: Get current date
        id: date
        run:  echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - run: |
            echo "::setting target domain::"
            echo "target=`cat target.txt`" >> $GITHUB_ENV
            echo "::endgroup::"
        shell: bash

      - run: |
          mkdir -p ~/result/amass
          mkdir -p ~/result/httpx
          echo ${{ env.target }} > ~/result/target.txt
          echo "${{ steps.date.outputs.date }}"

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.target }}-${{ steps.date.outputs.date }}
          path: ~/result/**/*